apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
kind: namespace
metadata:
  name: mv-hello-world
spec:
  containers:
  - name: hello-world
    image: mvasudev23/hello-world-app
    ports:
    - name: nodejs-port
      containerPort: 3000
